### DISCUSSION TITLE
New Installation cant restart Container, all data gone

### DISCUSSION THREAD

**Discussion by Thrandu** [thedevs-network/kutt#895] [Q&A]
--nervermind--

**Comment by poeti8** [comment]
![2025-04-24 12 36 22](https://github.com/user-attachments/assets/0b459d4e-0f18-4da3-bc58-c818d4c33e85)

**Reply by Thrandu** [reply]
Good point. i dont know what the real issue was or is.
But i ready something that "kutt" uses his own sqlite so i use another way to deploy and now it works fine, even some database issues are gone, so search for other users links is working too.

This is my Code:

```
version: '3.8'

services:
  server:
    image: kutt/kutt:latest
    container_name: kutt-server
    volumes:
      - db_data_sqlite:/var/lib/kutt
      - custom:/kutt/custom
    environment:
      DB_FILENAME: "/var/lib/kutt/data.sqlite"
      REDIS_ENABLED: true
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: "SUPERSECRET"
      KUTT_SITE_URL: "https://short.example.com"
      DEFAULT_DOMAIN: "short.example.com"
    ports:
      - "8082:3000"
    depends_on:
      redis:
        condition: service_started
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: kutt-redis
    restart: always
    volumes:
      - redis_data:/data
    expose:
      - "6379"

volumes:
  db_data_sqlite:
  custom:
  redis_data:
```
