### ISSUE TITLE
 500 (Internal Server Error)

### ISSUE THREAD

**Issue by muhammethmrt** [thedevs-network/kutt#338]
User gives 500 error when signing up 
POST http://....com.tr/api/v2/auth/signup 500 (Internal Server Error)
can you help me ?

**Comment by Vikram-T** [comment]
I'm having the same issue. Did you figure it out by chance?

**Comment by Vikram-T** [comment]
Turns out it's probably an error with your .env file. Set `MAIL_SECURE=false` and use `MAIL_PORT=587` see if that fixes your issue

**Comment by muhammethmrt** [comment]
Sorry, the problem continues

**Comment by Vikram-T** [comment]
what's your mail setup?

**Comment by muhammethmrt** [comment]
yes mail setup is correct

**Comment by Vikram-T** [comment]
Post it here

**Comment by muhammethmrt** [comment]
MAIL_HOST="mail.....com.tr"
MAIL_PORT=587
MAIL_SECURE=false
MAIL_USER="destek@....com.tr"
MAIL_FROM="Destek"
MAIL_PASSWORD=***

**Comment by Vikram-T** [comment]
Huh, IDK then. One thing that helped me was using the example from nodemailer.com with my credentials. But if it isn't the mail I don't know if I can help you
```
"use strict";
const nodemailer = require("nodemailer");

// async..await is not allowed in global scope, must use a wrapper
async function main() {
  // Generate test SMTP service account from ethereal.email
  // Only needed if you don't have a real mail account for testing
  let testAccount = await nodemailer.createTestAccount();

  // create reusable transporter object using the default SMTP transport
  let transporter = nodemailer.createTransport({
    host: "smtp.ethereal.email",
    port: 587,
    secure: false, // true for 465, false for other ports
    auth: {
      user: testAccount.user, // generated ethereal user
      pass: testAccount.pass, // generated ethereal password
    },
  });

  // send mail with defined transport object
  let info = await transporter.sendMail({
    from: '"Fred Foo 👻" <foo@example.com>', // sender address
    to: "bar@example.com, baz@example.com", // list of receivers
    subject: "Hello ✔", // Subject line
    text: "Hello world?", // plain text body
    html: "<b>Hello world?</b>", // html body
  });

  console.log("Message sent: %s", info.messageId);
  // Message sent: <b658f8ca-6296-ccf4-8306-87d57a0b4321@example.com>

  // Preview only available when sending through an Ethereal account
  console.log("Preview URL: %s", nodemailer.getTestMessageUrl(info));
  // Preview URL: https://ethereal.email/message/WaQKMgKddxQDoou...
}

main().catch(console.error);
```

**Comment by muhammethmrt** [comment]
Is there a mail address I can reach you

**Comment by chovy** [comment]
why was this closed? i canj't signup either.

**Comment by ProfessorVarox** [comment]
I'm also experiencing that problem so I need to create a new issue

**Comment by YouveGotMeowxy** [comment]
Getting the same here.

All I did was grab the example docker-compose.yml and .env and try to run it.

I set my .env:

```
# App port to run on
PORT=3000

# The name of the site where Kutt is hosted
SITE_NAME=Testsite

# The domain that this website is on
DEFAULT_DOMAIN=localhost:3000

# Generated link length
LINK_LENGTH=6

# Postgres database credential details
DB_HOST=postgres
DB_PORT=5432
DB_NAME=postgres
DB_USER=oc_kutt
DB_PASSWORD=redacted
DB_SSL=false

# Redis host and port
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=

# Disable registration
DISALLOW_REGISTRATION=false

# Disable anonymous link creation
DISALLOW_ANONYMOUS_LINKS=true

# The daily limit for each user
USER_LIMIT_PER_DAY=100

# Create a cooldown for non-logged in users in minutes
# Set 0 to disable
NON_USER_COOLDOWN=0

# Max number of visits for each link to have detailed stats
DEFAULT_MAX_STATS_PER_LINK=5000

# Use HTTPS for links with custom domain
CUSTOM_DOMAIN_USE_HTTPS=false

# A passphrase to encrypt JWT. Use a long and secure key.
JWT_SECRET=redacted

# Admin emails so they can access admin actions on settings page
# Comma seperated
ADMIN_EMAILS=me@gmail.com

# Invisible reCaptcha secret key
# Create one in https://www.google.com/recaptcha/intro/
RECAPTCHA_SITE_KEY=
RECAPTCHA_SECRET_KEY=

# Google Cloud API to prevent from users from submitting malware URLs.
# Get it from https://developers.google.com/safe-browsing/v4/get-started
GOOGLE_SAFE_BROWSING_KEY=

# Google Analytics tracking ID for universal analytics.
# Example: UA-XXXX-XX
GOOGLE_ANALYTICS=
GOOGLE_ANALYTICS_UNIVERSAL=

# Google Analytics tracking ID for universal analytics
# This one is used for links
# GOOGLE_ANALYTICS_UNIVERSAL=

# Your email host details to use to send verification emails.
# More info on http://nodemailer.com/
# Mail from example "Kutt <support@kutt.it>". Leave empty to use MAIL_USER
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_SECURE=false
MAIL_requireTLS=true
MAIL_USER="me@gmail.com"
MAIL_FROM="Test"
MAIL_PASSWORD="redacted"

# The email address that will receive submitted reports.
REPORT_EMAIL=me@gmail.com

# Support email to show on the app
CONTACT_EMAIL=
```

my compose:

```
version: "3"

services:
  kutt:
    image: kutt/kutt
    depends_on:
      - postgres
      - redis
    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "start"]
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_NAME: kutt
      DB_USER: user
      DB_PASSWORD: pass
      REDIS_HOST: redis

  redis:
    image: redis:6.0-alpine
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: kutt
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:
```

Then when entering an email and pw, and clicking sign up, I get (getting an error when directly trying to paste the image):
https://imgur.com/a/6o9nD93
