### ISSUE TITLE
Kutt docker behind nginx get redirected

### ISSUE THREAD

**Issue by Lapotor** [thedevs-network/kutt#389]
Hello.
i use the docker-compose version of kutt.it
I tried today to set it up behind an nginx reverse proxy.
So the version of kutt is 2.7.0

The domain i use get routed through cloudflare.

When i try to connect to the domain i get a redirect error.
If i change the port on `DEFAULT_DOMAIN` it always redirects me to the domain with the port attached.
I need to use another port as `3000` because it's already taken.

I hope you can help to solve this.

---
### Configs 
docker-compose.yml
```yaml
version: "3"

services:
  kutt:
    image: kutt/kutt
    depends_on:
      - postgres
      - redis
    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "start"]
    ports:
      - "4000:3000"
    env_file:
      - .docker.env
    environment:
      DB_HOST: postgres
      DB_NAME: kutt
      DB_USER: user
      DB_PASSWORD: pass
      REDIS_HOST: redis

  redis:
    image: redis:6.0-alpine
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: kutt
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:

```

.docker.env
```env
# App port to run on
PORT=3000

# The domain that this website is on
SITE_NAME=<NAME>

# The domain that this website is on
DEFAULT_DOMAIN=<DOMAIN.tld>:443

# Generated link length
LINK_LENGTH=6

# Postgres database credential details
DB_HOST=postgres
DB_PORT=5432
DB_NAME=postgres
DB_USER=
DB_PASSWORD=
DB_SSL=false

# ONLY NEEDED FOR MIGRATION !!1!
# Neo4j database credential details
NEO4J_DB_URI=bolt://localhost
NEO4J_DB_USERNAME=neo4j
NEO4J_DB_PASSWORD=BjEphmupAf1D5pDD

# Redis host and port
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=

# Disable registration
DISALLOW_REGISTRATION=true

# Disable anonymous link creation
DISALLOW_ANONYMOUS_LINKS=true

# The daily limit for each user
USER_LIMIT_PER_DAY=50

# Create a cooldown for non-logged in users in minutes
# Set 0 to disable
NON_USER_COOLDOWN=0

# Max number of visits for each link to have detailed stats
DEFAULT_MAX_STATS_PER_LINK=5000

# Use HTTPS for links with custom domain
CUSTOM_DOMAIN_USE_HTTPS=true

# A passphrase to encrypt JWT. Use a long and secure key.
JWT_SECRET=<SECRET>

# Admin emails so they can access admin actions on settings page
# Comma seperated
ADMIN_EMAILS=<ADMIN@MAIL>

# Invisible reCaptcha secret key
# Create one in https://www.google.com/recaptcha/intro/
RECAPTCHA_SITE_KEY=<SITE-KEY>
RECAPTCHA_SECRET_KEY=<SECRET-KEY>

# Google Cloud API to prevent from users from submitting malware URLs.
# Get it from https://developers.google.com/safe-browsing/v4/get-started
GOOGLE_SAFE_BROWSING_KEY=

# Google Analytics tracking ID for universal analytics.
# Example: UA-XXXX-XX
GOOGLE_ANALYTICS=
GOOGLE_ANALYTICS_UNIVERSAL=

# Google Analytics tracking ID for universal analytics
# This one is used for links
# GOOGLE_ANALYRICS_UNIVERSAL=

# Your email host details to use to send verification emails.
# More info on http://nodemailer.com/
# Mail from example "Kutt <support@kutt.it>". Leave empty to use MAIL_USER
MAIL_HOST=
MAIL_PORT=
MAIL_SECURE=true
MAIL_USER=
MAIL_FROM=
MAIL_PASSWORD=

# The email address that will receive submitted reports.
REPORT_EMAIL=<REPORT@MAIL>

# Support email to show on the app
CONTACT_EMAIL=<CONTACT@MAIL>
```

nginx.config
```nginx
# Advanced config for NGINX
        server_tokens off;
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Content-Type-Options nosniff;

# Redirect all HTTP traffic to HTTPS
server {
        listen 80;
        server_name domain.tld;
        return 301 https://$host$request_uri;
}

# SSL configuration
server {
        listen 443 ssl http2;
        server_name domain.tld;
        ssl_certificate /etc/ssl/live/domain/cert.pem;
        ssl_certificate_key /etc/ssl/live/domain/privkey.pem;

        # Improve HTTPS performance with session resumption
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 5m;

        # Disable SSLv3
        ssl_protocols TLSv1.2;

        # Enable OCSP stapling (http://blog.mozilla.org/security/2013/07/29/ocsp-stapling-in-firefox)
        resolver 1.1.1.1 1.0.0.1 valid=300s;
        resolver_timeout 5s;
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        location / {
                proxy_pass http://localhost:4000;

                proxy_http_version                 1.1;
                proxy_cache_bypass                 $http_upgrade;

                # Proxy headers
                proxy_set_header Upgrade           $http_upgrade;
                proxy_set_header Connection        "upgrade";
                proxy_set_header Host              $host;
                proxy_set_header X-Real-IP         $remote_addr;
                proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Host  $host;
                proxy_set_header X-Forwarded-Port  $server_port;

                # Proxy timeouts
                proxy_connect_timeout              60s;
                proxy_send_timeout                 60s;
                proxy_read_timeout                 60s;

        }

        location /api/url/sharex {
                proxy_pass        http://localhost:4000/api/url/submit;
                proxy_redirect    off;
                proxy_set_header  Upgrade $http_upgrade;
                proxy_set_header  Connection "upgrade";
                proxy_set_header  Host $host;
                proxy_set_header  X-Real-IP $remote_addr;
                proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header  X-Forwarded-Proto $scheme;
                proxy_set_header Content-Type application/json;
                proxy_set_body $http_target;
        }
}
```

**Comment by poeti8** [comment]
You don't need to provide port on `DEFAULT_DOMAIN`

**Comment by soneji** [comment]
I am also having a similar issue. When I go to example.com it redirects my browser to localhost:3000.

Here are my config files.
docker-compose.yml:
```yaml
version: "3"

services:
  kutt:
    image: kutt/kutt
    depends_on:
      - postgres
      - redis
    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "start"]
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_NAME: kutt
      DB_USER: user
      DB_PASSWORD: pass
      REDIS_HOST: redis

  redis:
    image: redis:6.0-alpine
    volumes:
      - ./redis_data:/data

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: kutt
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
```
.env
```
# App port to run on
PORT=3000

# The name of the site where Kutt is hosted
SITE_NAME=example.com

# The domain that this website is on
DEFAULT_DOMAIN=example.com

# Generated link length
LINK_LENGTH=6

# Postgres database credential details
DB_HOST=postgres
DB_PORT=5432
DB_NAME=postgres
DB_USER=
DB_PASSWORD=
DB_SSL=false

# ONLY NEEDED FOR MIGRATION !!1!
# Neo4j database credential details
NEO4J_DB_URI=bolt://localhost
NEO4J_DB_USERNAME=neo4j
NEO4J_DB_PASSWORD=BjEphmupAf1D5pDD

# Redis host and port
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=

# Disable registration
DISALLOW_REGISTRATION=false

# Disable anonymous link creation
DISALLOW_ANONYMOUS_LINKS=false

# The daily limit for each user
USER_LIMIT_PER_DAY=50000

# Create a cooldown for non-logged in users in minutes
# Set 0 to disable
NON_USER_COOLDOWN=0

# Max number of visits for each link to have detailed stats
DEFAULT_MAX_STATS_PER_LINK=5000

# Use HTTPS for links with custom domain
CUSTOM_DOMAIN_USE_HTTPS=false

# A passphrase to encrypt JWT. Use a long and secure key.
JWT_SECRET=securekey

# Admin emails so they can access admin actions on settings page
# Comma seperated
ADMIN_EMAILS=

# Invisible reCaptcha secret key
# Create one in https://www.google.com/recaptcha/intro/
# RECAPTCHA_SITE_KEY=
# RECAPTCHA_SECRET_KEY=

# Google Cloud API to prevent from users from submitting malware URLs.
# Get it from https://developers.google.com/safe-browsing/v4/get-started
GOOGLE_SAFE_BROWSING_KEY=

# Google Analytics tracking ID for universal analytics.
# Example: UA-XXXX-XX
GOOGLE_ANALYTICS=
GOOGLE_ANALYTICS_UNIVERSAL=

# Google Analytics tracking ID for universal analytics
# This one is used for links
# GOOGLE_ANALYTICS_UNIVERSAL=

# Your email host details to use to send verification emails.
# More info on http://nodemailer.com/
# Mail from example "Kutt <support@kutt.it>". Leave empty to use MAIL_USER
MAIL_HOST=mail.example.com
MAIL_PORT=465
MAIL_SECURE=true
MAIL_USER=info@example.com
MAIL_FROM=Link Shortener
MAIL_PASSWORD=password

# The email address that will receive submitted reports.
REPORT_EMAIL=tech@example.com

# Support email to show on the app
CONTACT_EMAIL=tech@example.com
```
nginx conf file
```
server {

    server_name example.com;

    location / {
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-Host $host:$server_port;
	proxy_set_header X-Forwarded-Server $host;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_pass http://localhost:3000;
    }
    location = /robots.txt { return 200 "User-agent: *\nDisallow: /\n"; }


    listen [::]:80;
    listen 80;

}
```
