### ISSUE TITLE
Can't connect to the app no matter what. Deployed through Docker.

### ISSUE THREAD

**Issue by Jas-SinghFSU** [thedevs-network/kutt#724]
No matter what I do, I can't access the server. I get connection timeout errors or "refused to connect" errors. My server's local IP address is 10.0.0.239 and that's the address I want to host it at. 

No matter what I do, the log for the container says 
```
Ready on http://localhost:3030
```
Even though I never specified `localhost` as the domain, it always tells me that the app is read on localhost:3030. I have tried to access localhost:3030 on my server and still get 'The site can't be reached'. I also have my own `subdomain.domain.com` but when I put that into the `DEFAULT_DOMAIN` it doesn't work either.

Here are my configs, what am I doing wrong?

Compose config using portainer
```yml
version: "3"

services:
  kutt:
    image: kutt/kutt
    depends_on:
      - postgres
      - redis
    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "start"]
    ports:
      - "3030:3000"
    env_file:
      - stack.env
    environment:
      DB_HOST: postgres
      DB_NAME: kuttgres
      DB_USER: <db_user>
      DB_PASSWORD: <db_pass>
      REDIS_HOST: redis

  redis:
    image: redis:6.0-alpine
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: <db_user>
      POSTGRES_PASSWORD: <db_pass>
      POSTGRES_DB: kuttgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:
```

docker.env
```env
# App port to run on
PORT=3030

# The name of the site where Kutt is hosted
SITE_NAME=Kutt

# The domain that this website is on
DEFAULT_DOMAIN=0.0.0.0:3030
# Have also tried the following. My local server ip address is 10.0.0.239 (where I want to host it)
#DEFAULT_DOMAIN=10.0.0.239:3030
#DEFAULT_DOMAIN=0.0.0.0
#DEFAULT_DOMAIN=10.0.0.239
#DEFAULT_DOMAIN=0.0.0.0:3030
# And all of the above with http:// in the beginning as well

# Generated link length
LINK_LENGTH=6

# Postgres database credential details
DB_HOST=postgres
DB_PORT=5432
DB_NAME=kuttgres
DB_USER=<db_user>
DB_PASSWORD=<db_pass>
DB_SSL=false

# Redis host and port
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=
REDIS_DB=

# Disable registration
DISALLOW_REGISTRATION=false

# Disable anonymous link creation
DISALLOW_ANONYMOUS_LINKS=false

# The daily limit for each user
USER_LIMIT_PER_DAY=50

# Create a cooldown for non-logged in users in minutes
# Set 0 to disable
NON_USER_COOLDOWN=0

# Max number of visits for each link to have detailed stats
DEFAULT_MAX_STATS_PER_LINK=5000

# Use HTTPS for links with custom domain
CUSTOM_DOMAIN_USE_HTTPS=false

# A passphrase to encrypt JWT. Use a long and secure key.
JWT_SECRET=<my_secure_key>

# Admin emails so they can access admin actions on settings page
# Comma seperated
ADMIN_EMAILS= <my_emails>

# Invisible reCaptcha secret key
# Create one in https://www.google.com/recaptcha/intro/
RECAPTCHA_SITE_KEY=<my_site_key>
RECAPTCHA_SECRET_KEY=<my_site_secret>

# Google Cloud API to prevent from users from submitting malware URLs.
# Get it from https://developers.google.com/safe-browsing/v4/get-started
GOOGLE_SAFE_BROWSING_KEY=

# Your email host details to use to send verification emails.
# More info on http://nodemailer.com/
# Mail from example "Kutt <support@kutt.it>". Leave empty to use MAIL_USER
MAIL_HOST=<my_credentials>
MAIL_PORT=<my_credentials>
MAIL_SECURE=true
MAIL_USER=<my_credentials>
MAIL_FROM=<my_credentials>
MAIL_PASSWORD=<my_credentials>

# The email address that will receive submitted reports.
REPORT_EMAIL=<my_credentials>

# Support email to show on the app
CONTACT_EMAIL=<my_credentials>
```
