### ISSUE TITLE
Problem with the database

### ISSUE THREAD

**Issue by bulava92** [thedevs-network/kutt#908]
<img width="499" alt="Image" src="https://github.com/user-attachments/assets/563bfdbe-9be8-486f-ba83-5b5c8e60ac0e" />

After each
```
root@aciszlyssn:~/kutt# docker-compose down
[+] Running 3/3
 ✔ Container kutt-kutt-1  Removed                                                                                                                                   0.7s 
 ✔ Container kutt-db-1    Removed                                                                                                                                   0.1s 
 ✔ Network kutt_default   Removed                                                                                                                                   0.1s 
root@aciszlyssn:~/kutt# docker-compose up -d
[+] Building 0.0s (0/0)                                                                                                                      docker-container:brave_jang
[+] Running 3/3
 ✔ Network kutt_default   Created                                                                                                                                   0.1s 
 ✔ Container kutt-db-1    Started                                                                                                                                   0.0s 
 ✔ Container kutt-kutt-1  Started                                                                                                                                   0.0s 
root@aciszlyssn:~/kutt# 
```
Offers to recreate an admin and the created links are not saved
What can I check?

```
root@aciszlyssn:~/kutt# docker logs -f kutt-kutt-1

> kutt@3.2.3 migrate
> knex migrate:latest

Batch 1 run: 10 migrations
npm notice
npm notice New major version of npm available! 10.9.2 -> 11.3.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.3.0
npm notice To update run: npm install -g npm@11.3.0
npm notice

> kutt@3.2.3 start
> node server/server.js --production

> Ready on http://localhost:3000

```

```
  GNU nano 7.2                                                          /root/kutt/docker-compose.yml                                                                    
version: '3.8'

services:
  kutt:
    image: ghcr.io/rophy/kutt:main
    restart: always
    environment:
      - DEFAULT_DOMAIN=xxx
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=kutt
      - DB_USER=kuttuser
      - DB_PASSWORD=supersecret
      - SITE_NAME=Kutt
      - SITE_DESCRIPTION=Self-hosted URL shortener
      - ADMIN_EMAIL=xxx
      - DISALLOW_REGISTRATION=true
      - DISALLOW_FORM_LOGIN=false
      - JWT_SECRET=changeme-supersecret-key
      - MAIL_HOST=xxx
      - MAIL_PORT=2525
      - MAIL_SECURE=false
      - MAIL_USER=xxx
      - MAIL_PASSWORD=xxx
      - MAIL_FROM=Kutt <xxx>

    depends_on:
      - db
    ports:
      - "3005:3000"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: kutt
      POSTGRES_USER: kuttuser
      POSTGRES_PASSWORD: supersecret
    volumes:
      - kutt-db-data:/var/lib/postgresql/data

volumes:
  kutt-db-data:
```
